apiVersion: v1
kind: Template
metadata:
  name: ops-zabbix-monitoring
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      name: centos
    name: centos
  spec:
    dockerImageRepository: library/centos:latest
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      name: oso-centos-ops-base
    name: oso-centos-ops-base
  spec:
    tags:
    - from:
        kind: DockerImage
        name: library/oso-centos-ops-base:latest
      name: latest
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      name: oso-centos-zabbix-server
    name: oso-centos-zabbix-server
  spec: {}
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      name: oso-centos-zabbix-web
    name: oso-centos-zabbix-web
  spec: {}
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      name: oso-rhel7-zagg-web
    name: oso-rhel7-zagg-web
  spec: {}
- apiVersion: v1beta3
  kind: DeploymentConfig
  metadata:
    labels:
      name: ${DATABASE_SERVICE_NAME}
    name: ${DATABASE_SERVICE_NAME}
  spec:
    replicas: 1
    selector:
      name: ${DATABASE_SERVICE_NAME}
    strategy:
      resources: {}
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          name: ${DATABASE_SERVICE_NAME}
      spec:
        containers:
        - capabilities: {}
          env:
          - name: MYSQL_USER
            value: ${MYSQL_USER}
          - name: MYSQL_PASSWORD
            value: ${MYSQL_PASSWORD}
          - name: MYSQL_DATABASE
            value: ${MYSQL_DATABASE}
          - name: MYSQL_ROOT_PASSWORD
            value: ${MYSQL_PASSWORD}
          image: openshift/mysql-55-centos7:latest
          imagePullPolicy: IfNotPresent
          name: mysql
          ports:
          - containerPort: 3306
            protocol: TCP
          resources: {}
          securityContext:
            capabilities: {}
            privileged: false
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - mysql
        from:
          kind: ImageStreamTag
          name: mysql:latest
          namespace: openshift
        lastTriggeredImage: ''
      type: ImageChange
    - type: ConfigChange
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      name: oso-centos-zabbix-server
    name: oso-centos-zabbix-server
  spec:
    replicas: 1
    selector:
      deploymentconfig: oso-centos-zabbix-server
    strategy:
      resources: {}
      type: Recreate
    template:
      metadata:
        labels:
          deploymentconfig: oso-centos-zabbix-server
      spec:
        containers:
        - env:
          - name: MYSQL_USER
            value: ${MYSQL_USER}
          - name: MYSQL_PASSWORD
            value: ${MYSQL_PASSWORD}
          - name: MYSQL_DATABASE
            value: ${MYSQL_DATABASE}
          - name: MYSQL_HOST
            value: ${DATABASE_SERVICE_NAME}
          image: docker.io/rhmap/oso-centos-zabbix-server:latest
          imagePullPolicy: IfNotPresent
          name: oso-centos-zabbix-server
          ports:
          - containerPort: 10050
            name: tcp-10050
            protocol: TCP
          - containerPort: 10051
            name: tcp-10051
            protocol: TCP
          resources: {}
          securityContext:
            capabilities: {}
            privileged: false
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
    triggers:
    - type: ConfigChange
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      name: oso-centos-zabbix-web
    name: oso-centos-zabbix-web
  spec:
    replicas: 1
    selector:
      deploymentconfig: oso-centos-zabbix-web
    strategy:
      resources: {}
      type: Recreate
    template:
      metadata:
        labels:
          deploymentconfig: oso-centos-zabbix-web
      spec:
        containers:
        - env:
          - name: MYSQL_USER
            value: ${MYSQL_USER}
          - name: MYSQL_PASSWORD
            value: ${MYSQL_PASSWORD}
          - name: MYSQL_DATABASE
            value: ${MYSQL_DATABASE}
          - name: MYSQL_HOST
            value: ${DATABASE_SERVICE_NAME}
          image: docker.io/rhmap/oso-centos-zabbix-web:latest
          imagePullPolicy: IfNotPresent
          name: oso-centos-zabbix-web
          ports:
          - containerPort: 80
            name: tcp-80
            protocol: TCP
          - containerPort: 443
            name: tcp-443
            protocol: TCP
          resources: {}
          securityContext:
            capabilities: {}
            privileged: false
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
    triggers:
    - type: ConfigChange
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      name: oso-rhel7-zagg-web
    name: oso-rhel7-zagg-web
  spec:
    replicas: 1
    selector:
      deploymentconfig: oso-rhel7-zagg-web
    strategy:
      resources: {}
      type: Recreate
    template:
      metadata:
        labels:
          deploymentconfig: oso-rhel7-zagg-web
      spec:
        containers:
        - image: docker.io/rhmap/oso-rhel7-zagg-web:latest
          imagePullPolicy: IfNotPresent
          name: oso-rhel7-zagg-web
          resources: {}
          securityContext:
            capabilities: {}
            privileged: false
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
    triggers:
    - type: ConfigChange
- apiVersion: v1
  kind: Route
  metadata:
    name: zabbix-web-route
  spec:
    host: ${ZABBIX_WEB_URL}
    to:
      kind: Service
      name: oso-centos-zabbix-web
- apiVersion: v1
  kind: Route
  metadata:
    name: zagg-web-route
  spec:
    host: ${ZAGG_WEB_URL}
    to:
      kind: Service
      name: oso-rhel7-zagg-web
- apiVersion: v1beta3
  kind: Service
  metadata:
    creationTimestamp: null
    name: ${DATABASE_SERVICE_NAME}
  spec:
    portalIP: ''
    ports:
    - name: mysql
      nodePort: 0
      port: 3306
      protocol: TCP
      targetPort: 3306
    selector:
      name: ${DATABASE_SERVICE_NAME}
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      name: oso-centos-zabbix-server
    name: oso-centos-zabbix-server
  spec:
    ports:
    - name: tcp-10050
      nodePort: 0
      port: 10050
      protocol: TCP
      targetPort: 10050
    - name: tcp-10051
      nodePort: 0
      port: 10051
      protocol: TCP
      targetPort: 10051
    selector:
      deploymentconfig: oso-centos-zabbix-server
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      name: oso-centos-zabbix-web
    name: oso-centos-zabbix-web
  spec:
    ports:
    - name: tcp-80
      nodePort: 0
      port: 80
      protocol: TCP
      targetPort: 8000
    - name: tcp-443
      nodePort: 0
      port: 443
      protocol: TCP
      targetPort: 8000
    selector:
      deploymentconfig: oso-centos-zabbix-web
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      name: oso-rhel7-zagg-web
    name: oso-rhel7-zagg-web
  spec:
    ports:
    - name: http
      nodePort: 0
      port: 80
      protocol: TCP
      targetPort: 8000
    - name: https
      nodePort: 0
      port: 443
      protocol: TCP
      targetPort: 8000
    selector:
      deploymentconfig: oso-rhel7-zagg-web
    sessionAffinity: None
    type: ClusterIP
parameters:
- description: Database service name
  name: DATABASE_SERVICE_NAME
  value: mysql
- description: Username for MySQL user that will be used for accessing the database
  from: user[A-Z0-9]{3}
  generate: expression
  name: MYSQL_USER
- description: Password for the MySQL user
  from: '[a-zA-Z0-9]{16}'
  generate: expression
  name: MYSQL_PASSWORD
- description: Database name
  name: MYSQL_DATABASE
  value: zabbix
- description: Volume space available for data, e.g. 512Mi, 2Gi
  name: VOLUME_CAPACITY
  value: 10Gi
- description: Zabbix web ui URL
  name: ZABBIX_WEB_URL
  value: oso-centos-zabbix-web
- description: Zagg web URL
  name: ZAGG_WEB_URL
  value: oso-rhel7-zagg-web
- description: Zabbix server
  name: ZABBIX_SERVER
  value: oso-centos-zabbix-server
- description: Zabbix web user
  name: ZABBIX_WEB_USER
  value: Admin
- description: Zabbix web password
  name: ZABBIX_WEB_PASSWORD
  value: zabbix
